# Emacs 스타일 키바인딩
# Emacs의 일반적인 키 조합을 따릅니다.
# Ctrl 키: C-a, C-b, C-c 등 (Ctrl + 문자)

keybindings:
  # 애플리케이션 종료 (Ctrl-q for Quit)
  quit: ['C-q']
  
  # Todo 추가 모드로 전환 (Ctrl-a for Add)
  add_todo: ['C-a']
  
  # Todo 완료 상태 토글 (Ctrl-c for Change)
  toggle_complete: ['C-c', 'Space']
  
  # Todo 삭제 (Ctrl-k for kill line)
  delete_todo: ['C-k']
  
  # 목록 탐색 (Ctrl-p/Ctrl-n for previous/next)
  navigate_up: ['C-p', 'Up']
  navigate_down: ['C-n', 'Down']
  
  # 입력 모드에서 저장 (Ctrl-s for Save)
  save_input: ['C-s', 'Enter']
  
  # 입력 모드에서 취소 (Ctrl-G)
  cancel_input: ['C-g', 'Esc']
  
  # Todo 편집 (Ctrl-e for Edit)
  edit_todo: ['C-e', 'e']
